### PR TITLE
"oadm create-server-cert" command relocated under "oadm ca"

### PR DESCRIPTION
**Pull request by ryanj**
For this issue: https://github.com/2015-Middleware-Keynote/demo-ansible/issues/70

### CODE REVIEW

**Comment by detiber** [comment]
/etc/origin is the correct path for 3.1, are you sure the 3.1 binaries were installed instead of 3.0 and the deployment_type is openshift-enterprise.

You may want to try Erik's branch, since he's made additional changes to my branch already.

**Comment by ryanj** [comment]
sorry, just realized that...  `/etc/origin` is indeed correct for the newer deployment_types.
https://github.com/openshift/openshift-ansible/blob/master/DEPLOYMENT_TYPES.md#deployment-types

I didn't include a `--deployment_type` flag, and the default value caused a failure when it encountered the newer folder layout.

I'll revert those changes and try `origin` and `atomic-enterprise` for the `deployment-type`:

```
./run.py --env-size medium --master-instance-type t2.large --infra-instance-type c3.xlarge --node-instance-type r3.large --keypair roadshow --r53-zone openshift3roadshow.com --app-dns-prefix apps --skip-subscription-management --rhsm-user foo --rhsm-pass bar --default-password examplepasswd --console-port 443 --api-port 443 --num-smoke-test-users 0 --region us-west-1 --ami ami-9b40a5df --deployment-type origin --cluster-id example
```

**Comment by detiber** [comment]
You'll want to use openshift-enterprise and not atomic-enterprise.

@thoraxe's branch is here: https://github.com/thoraxe/demo-ansible/tree/3_1_support. I believe he updated the default Deployment_type there already.

**Comment by ryanj** [comment]
I get this error with every `--deployment_type` (except `origin`): https://github.com/2015-Middleware-Keynote/demo-ansible/issues/71

I'll take a look at Erik's changes...

**Comment by ryanj** [comment]
I've cleaned up this PR and adjusted the title, limiting the focus to the deprecation of "oadm create-server-cert".

**Comment by ryanj** [comment]
@detiber It looks like your 3_1_support branch has all of @thoraxe's recent changes, or I'd give that branch a try as well.

**Pull request closed without merging**
